### ISSUE TITLE
Error occured with additional blank line(s) in txt data file

### ISSUE THREAD

**Issue by NoNormalCreeper** [CSBigCaptain/CaptainWordTester#1]
### Trace back：
```
Traceback (most recent call last):
  File "D:\Files\coding\Python\CaptainWordTester-main\mainp.py", line 19, in <module>
    fuctions.modeA(finalList)
  File "D:\Files\coding\Python\CaptainWordTester-main\fuctions.py", line 148, in modeA
    askedList = valueList(finalList)
  File "D:\Files\coding\Python\CaptainWordTester-main\fuctions.py", line 125, in valueList
    list = [i ,littleList[1]]
IndexError: list index out of range

[process exited with code 1]
```

### `MainFile.txt`s for test
**(A)**
```
solve 解决

```

**(B)**
```

solve 解决
```

**Comment by CSBigCaptain** [comment]
Yes,It is one of the **txt mode**'s disadvantages,I can't repair the problem quickly.I advise you to use the **json mode**🤣🤣.
I will write the new **Readme.md** to show these problems!

**Comment by NoNormalCreeper** [comment]
sorry, but solving this bug is **quite easy**.

set the string u read from the file called `mystr`, then run
```
new_str = "".join([s for s in mystr.splitlines(True) if s.strip()]).strip()
```

after that, `new_str` will not include blank line(s).

**Comment by CSBigCaptain** [comment]
The reason why I must have a long time to repair these problems is my technology is not so powerful🤣🤣.
I increase my Python technology by these projects.
But ur idea may be useful because I don't know what's ur code doing.But I will find out your ideas!🤔🤔

**Comment by NoNormalCreeper** [comment]
dosent matter!
⛽ it is useful that doing projects to improve ur skills!

**Comment by NoNormalCreeper** [comment]
btw, writing in english requires u to **add a space** before ur **punctuation marks** (`,`, `.`, `!`, etc.).

For example:

>+ ❌ `Jack,slow f#ck!` 
>+ ❌ `Jack ,slow f#ck!`
>+ ❌ `Jack , slow f#ck!`
>+ ✔️ `Jack, slow f#ck!`

**Comment by NoNormalCreeper** [comment]
> The reason why I must have a long time to repair these problems is my technology is not so powerful🤣🤣. I increase my Python technology by these projects. But ur idea may be useful because I don't know what's ur code doing.But I will find out your ideas!🤔🤔

My code roughly means

```
new_str = ""
for s in mystr.splitlines(True):
    if s.strip():
        new_str.join(s)
new_str = new_str.strip()
```
